baseURL = "https://charline44442.github.io/erdads/"
title = "教師のためのAI・DS研究開発センター"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "ja"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "ja"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[services]
    # Enable comments by entering your Disqus shortname
    [services.disqus]
        shortname = ""
    # Enable Google Analytics by entering your tracking code
    [services.googleAnalytics]
        id = ""

# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]
[[menu.main]]
    name       = "HOME"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "ニュース"
    identifier = "menu.2"
    url        = "/news/"
    weight     = 2

#[[menu.main]]
#    name       = "センター紹介"
#    url        = "/"
#    weight     = 1
#    parent     = "menu.2"

[[menu.main]]
    name       = "センターについて"
    identifier = "menu.3"
    url        = "/center/"
    weight     = 3

[[menu.main]]
    name       = "スタッフ紹介"
    identifier = "menu.4"
    url        = "/#staff"
    weight     = 4  
    
[[menu.main]]
    name       = "研究紹介"
    identifier = "menu.5"
    url        = "/research/"
    weight     = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "X"
    url = "https://x.com"
    pre = "<i class='fab fa-2x fa-x-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    # Remplacer l'ancien lien du bouton "view more"
    viewMorePostLink = "/news/"
    author = "DevCows"
    defaultKeywords = ["devcows", "hugo", "go"]
    # Remplacer la section principale
    mainSections = ["news"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # :( KEY !! Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "28.43268"
    longitude = "77.0459"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = """<p class="text-uppercase"><strong>鳴門教育大学</strong>
        <br><strong>教師のためのAI・DS研究開発センター</strong>
        <br>〒772-8502 徳島県鳴門市鳴門町高島字中島748番地
        <br>国立大学法人鳴門教育大学
      </p>
      """
    copyright = "©Center for Educational Research and Development in AI and Data Science. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Universal"

    logo = "img/naruto-full-logo.png"
    logo_small = "img/naruto-logo.jpg"
    contact_url = "/contact" #changer le lien du bouton contact ?
    address = '''<p class="footer-contact">経営企画戦略課：kikaku<img src="img/at.png" alt="@" class="at-symbol">naruto-u.ac.jp</p>'''

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 4000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 4 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.
    title = "About"
    subtitle = ""

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "RELATED SITES"
    subtitle = "関連サイト"

[params.recent_posts]
    enable = true
    title = "新着情報"
    subtitle = ""
    hide_summary = true

[params.footer.recent_posts]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"

